### PR TITLE
Feature/sign-up--skip

### PR DESCRIPTION
**Pull request by tim-nguyen-cs**
Problem
---
As a user, I would like to log into my Cboard account to receive relevant account information.

[Link to Notion ticket](https://www.notion.so/Skipped-Sign-Up-User-Flow-9dba5f47635c41fbbce37b27cbd74b06).

Key Changes
---
* Implemented the "Sign Up" view when a user would not like to make an account
* Implemented the "Install TTS" view to show the user how to download the appropriate text-to-speech resource.
* Implemented the TTS dialog box if the appropriate package was not found
* Implemented a global `Typography` file to source common common typography classes.
* Outlined a "Select Voice" view
* Extracted `FlatButton` into a shared `Button` widget
* Standardized styling definitions on `EdgeInsets.symmetric`

### CODE REVIEW

**Review by darrenzhang2000 — COMMENTED** [review]
Hey @tim-nguyen-cs  Thanks for all the efforts you're putting into this project. The naming conventions, widgets modularity, and overall code look amazing!

I'm currently running the app on the Pixel 3a, which has a longer height than traditional androids. Do you mind making the screens responsive for devices with different width/height? 
Here are the images for what I'm seeing.

image

image

@zachmothner Do you have any suggestions?

**Comment by tim-nguyen-cs** [comment]
@darrenzhang2000 Ahh, thanks for pointing that out! I didn't configure that yet, just because I also was going to ask for feedback out component sizing! Do you have any recommendations about how to scale a container to fit the entire height of a view box? I've been been able to hard-code parameters, but I don't think that's very efficient. 

What else should we do?

**Comment by darrenzhang2000** [comment]
@tim-nguyen-cs Not sure if this is the best idea, but it seems you can the height of the container using media query and context? https://alvinalexander.com/source-code/how-to-set-size-flutter-container-height-width/
`height: MediaQuery.of(context).size.height - 270,` seems to be the height of everything excluding the appbar. 

Have you tried using the Expanded Widget? https://api.flutter.dev/flutter/widgets/Expanded-class.html
It's sort of similar to "flex grow" in css.

**Comment by tim-nguyen-cs** [comment]
@darrenzhang2000 Awesome! Those links where super helpful for me! I went ahead and made some changes, so let me know how they look. In our upcoming meeting this week, I think we should definitely talk about how we're going to consider responsive design when iterating through out prototypes!

**Comment by darrenzhang2000** [comment]
Looks good to me!

**Review by darrenzhang2000 — DISMISSED** [review]

**Review by darrenzhang2000 — APPROVED** [review]

**Pull request merged**
